## Imports

In [2]:
import time

import numpy as np
import cv2 as cv
import os
import glob
import matplotlib.pyplot as plt
from cv2 import cvtColor
from numpy.random import uniform
import pdb
from tqdm import tqdm

import utils
from utils import show_image_matplot,show_image_cv

In [3]:
game_tables = utils.extract_game(utils.get_image_paths("antrenare",1))

100%|██████████| 50/50 [00:14<00:00,  3.46it/s]


In [4]:
relevant_game_tables = utils.extract_relevant_game(game_tables)

100%|██████████| 50/50 [00:00<00:00, 96.10it/s]


In [5]:
delimited_tables = utils.draw_lines(relevant_game_tables)

100%|██████████| 50/50 [00:00<00:00, 921.42it/s]


In [6]:
# utils.store_template_numbers1(10)
# utils.store_template_numbers2(8)

In [7]:
# utils.store_binary_templates(100,"./templates/sample1","./templates_binary/sample1")
# utils.store_binary_templates(100)

In [8]:
# new_templates = crop_and_store_templates()

In [9]:
#utils.rewrite_all()

In [17]:
from utils import get_mathable_pieces_numbers, get_lines_coords

# def classify_number(patch,templates_path = "./templates_cropped"):
#     max_corr = -np.inf
#     chosen_number = -1
#     numbers = get_mathable_pieces_numbers()
#
#
#     for i in range(10,len(numbers)):
#
#         number = numbers[i]
#         template = cv.imread(templates_path+ "/" + str(number) + ".jpg")
#         template = cv.cvtColor(template, cv.COLOR_BGR2GRAY)
#
#         corr = cv.matchTemplate(patch,template, cv.TM_CCOEFF_NORMED)
#         corr=np.max(corr)
#
#         if corr > max_corr:
#             max_corr = corr
#             chosen_number = number
#
#     if max_corr >= 0.8:
#         return chosen_number
#
#     max_corr = -np.inf
#     chosen_number = -1
#
#     for i in range(0,10):
#
#         number = numbers[i]
#         template = cv.imread(templates_path+ "/" + str(number) + ".jpg")
#         template = cv.cvtColor(template, cv.COLOR_BGR2GRAY)
#
#         corr = cv.matchTemplate(patch,template, cv.TM_CCOEFF_NORMED)
#         corr=np.max(corr)
#
#         if corr > max_corr:
#             max_corr = corr
#             chosen_number = number
#
#
#     return chosen_number

def classify_number(patch,templates_path = "./templates_cropped"):

    maxi = -np.inf
    chosen_number = -1
    numbers = get_mathable_pieces_numbers()

    num_whites_patch = np.sum(patch == 255)

    for number in numbers:
        template = cv.imread(templates_path+ "/" + str(number) + ".jpg")
        template = cv.cvtColor(template, cv.COLOR_BGR2GRAY)

        num_whites_template = np.sum(template == 255)

        if num_whites_template * 1.95 < num_whites_patch:
            continue

        corr = cv.matchTemplate(patch,template, cv.TM_CCOEFF_NORMED)
        corr=np.max(corr)

        if corr > maxi:
            maxi = corr
            chosen_number = number


    return chosen_number

def match_numbers(binary_image, offset):
    lines_vertical,lines_horizontal = get_lines_coords()

    coords={}

    for i in range(len(lines_horizontal)-1):
        for j in range(len(lines_vertical)-1):

            y_min = lines_vertical[j][0][0] + offset
            y_max = lines_vertical[j + 1][1][0] - offset
            x_min = lines_horizontal[i][0][1] + offset
            x_max = lines_horizontal[i + 1][1][1] - offset

            patch = binary_image[x_min:x_max,y_min:y_max].copy()

            if (i==6 or i==7) and (j==6 or j==7):
                continue

            num_white_pixels = np.sum(binary_image[x_min+30:x_max-30,y_min+30:y_max-30].copy() == 255)

            if num_white_pixels > 0:
                predicted_number = classify_number(patch)
                coords[(i,j)] = predicted_number

    return coords

def get_patches(binary_image,offset):
    lines_vertical,lines_horizontal = get_lines_coords()

    patches = []

    for i in range(len(lines_horizontal)-1):
        for j in range(len(lines_vertical)-1):

            y_min = lines_vertical[j][0][0] + offset
            y_max = lines_vertical[j + 1][1][0] - offset
            x_min = lines_horizontal[i][0][1] + offset
            x_max = lines_horizontal[i + 1][1][1] - offset

            patch = binary_image[x_min:x_max,y_min:y_max].copy()

            patches.append(patch)

    return patches

In [11]:
def move_train_data(train_number,dest_path = "./train"):
    img_prefix = str(train_number)+ "_"

    for i in range(9):
        img_name = img_prefix + "0" +str(i+1) + ".jpg"
        img_path = "./antrenare/" + img_name
        img = cv.imread(img_path)
        cv.imwrite(dest_path +"/" + img_name, img)

    for i in range(9,50):
        img_path = "./antrenare/" + img_prefix + str(i+1) + ".jpg"
        img_name = img_prefix +str(i+1) + ".jpg"
        img = cv.imread(img_path)
        cv.imwrite(dest_path +"/" + img_name, img)

# for i in range(4):
#     move_train_data(i+1)



In [24]:

def solve(train_number,src_path = "./antrenare",output_dest_path = "./343_Gabroveanu_Razvan"):

    game_tables = utils.extract_game(utils.get_image_paths(src_path,train_number))
    relevant_game_tables = utils.extract_relevant_game(game_tables)

    visited = np.full((14,14),-1)

    visited[6,6] = 1
    visited[6,7] = 2
    visited[7,6] = 3
    visited[7,7] = 4

    output_file_prefix = "/" + str(train_number) + "_"

    for i in tqdm(range(len(relevant_game_tables))):

        table = relevant_game_tables[i]
        table = cv.cvtColor(table, cv.COLOR_BGR2GRAY)
        _,table_binary = cv.threshold(table,65,255,cv.THRESH_BINARY_INV)

        result_dict = match_numbers(table_binary,8)

        for indexes,predicted_number in result_dict.items():
            row,col = indexes

            if visited[row,col] == -1:
                continue

            output = str(row+1) + chr(65 + col)+ " " + str(predicted_number)
            output_file_path = output_dest_path + output_file_prefix

            if i in range(0,9):
                output_file_path = output_file_path + "0"

            output_file_path = output_file_path + str(i+1) + ".txt"

            with open(output_file_path,"w") as file:
                file.write(output)

            visited[row,col] = predicted_number

    with open(output_dest_path + "/" + str(train_number) + "_scores.txt","w") as file:
        pass

    with open(output_dest_path + "/" + str(train_number) + "_turns.txt","w") as file:
        pass

for i in range(4):
    solve(i+1)



100%|██████████| 50/50 [00:17<00:00,  2.90it/s]


In [13]:

game_tables2 = utils.extract_game(utils.get_image_paths("antrenare",2))
relevant_game_tables2 = utils.extract_relevant_game(game_tables2)

100%|██████████| 50/50 [00:00<00:00, 117.10it/s]


In [14]:

sample = relevant_game_tables2[0]
sample = cv.cvtColor(sample,cv.COLOR_BGR2GRAY)
_,sample = cv.threshold(sample,65,255,cv.THRESH_BINARY_INV)

show_image_cv("",sample,fx = 0.4,fy = 0.4)

coords = match_numbers(sample, offset = 8)
patches = get_patches(sample, offset = 8)

In [15]:
print(coords)

{(6, 8): 8}


In [16]:
for key,value in coords.items():
    index = key[0] * 14 + key[1]
    title = str(key[0]) + "," + str(key[1]) + " " + str(value)
    # show_image_cv(title,patches[index],fx = 1,fy = 1)

    three = cv.imread("templates_cropped/3.jpg")
    eight = cv.imread("templates_cropped/8.jpg")


    three = cv.cvtColor(three,cv.COLOR_BGR2GRAY)
    eight= cv.cvtColor(eight,cv.COLOR_BGR2GRAY)

    # _, three = cv.threshold(three, 128, 255, cv.THRESH_BINARY)
    # _, eight = cv.threshold(eight, 128, 255, cv.THRESH_BINARY)

    w3 = np.sum(three == 255)
    wp = np.sum(patches[index] == 255)

    corr1 = np.max(cv.matchTemplate(patches[index],three,cv.TM_CCOEFF_NORMED))
    corr2 = np.max(cv.matchTemplate(patches[index],eight,cv.TM_CCOEFF_NORMED))
    cv.imwrite("temp.jpg",patches[index])
    print(corr1,corr2)
    print(three.shape)
    print(eight.shape)
    print(patches[index].shape)
    print(w3,wp)
    print(classify_number(patches[index]))

0.8862497 0.7159185
(72, 45)
(71, 45)
(134, 134)
805 1660
8


In [37]:
class Solver():

    def __init__(self,data_set_id):

        self.data_set_id = data_set_id

        self.table_configuration = np.full((14,14),-1)
        self.table_configuration[6,6] = 1
        self.table_configuration[6,7] = 2
        self.table_configuration[7,6] = 3
        self.table_configuration[7,7] = 4

        self.ADD = 1
        self.SUB = 2
        self.MUL = 3
        self.DIV = 4
        self.TIMES_2 = 5
        self.TIMES_3 = 6

        self.table_constraints = np.array([
            [self.TIMES_3,0,0,0,0,0,self.TIMES_3,self.TIMES_3,0,0,0,0,0,self.TIMES_3],
            [0,self.TIMES_2,0,0,self.DIV,0,0,0,0,self.DIV,0,0,self.TIMES_2,0],
            [0,0,self.TIMES_2,0,0,self.SUB,0,0,self.SUB,0,0,self.TIMES_2,0,0],
            [0,0,0,self.TIMES_2,0,0,self.ADD,self.MUL,0,0,self.TIMES_2,0,0,0],
            [0,self.DIV,0,0,self.TIMES_2,0,self.MUL,self.ADD,0,self.TIMES_2,0,0,self.DIV,0],
            [0,0,self.SUB,0,0,0,0,0,0,0,0,self.SUB,0,0],
            [self.TIMES_3,0,0,self.MUL,self.ADD,0,0,0,0,self.MUL,self.ADD,0,0,self.TIMES_3],

            [self.TIMES_3,0,0,self.ADD,self.MUL,0,0,0,0,self.ADD,self.MUL,0,0,self.TIMES_3],
            [0,0,self.SUB,0,0,0,0,0,0,0,0,self.SUB,0,0],
            [0,self.DIV,0,0,self.TIMES_2,0,self.ADD,self.MUL,0,self.TIMES_2,0,0,self.DIV,0],
            [0,0,0,self.TIMES_2,0,0,self.MUL,self.ADD,0,0,self.TIMES_2,0,0,0],
            [0,0,self.TIMES_2,0,0,self.SUB,0,0,self.SUB,0,0,self.TIMES_2,0,0],
            [0,self.TIMES_2,0,0,self.DIV,0,0,0,0,self.DIV,0,0,self.TIMES_2,0],
            [self.TIMES_3,0,0,0,0,0,self.TIMES_3,self.TIMES_3,0,0,0,0,0,self.TIMES_3],

        ])

    def reset(self):
        self.table_configuration = np.full((14,14),-1)
        self.table_configuration[6,6] = 1
        self.table_configuration[6,7] = 2
        self.table_configuration[7,6] = 3
        self.table_configuration[7,7] = 4

    def solve(self,src_path = "./antrenare",output_dest_path = "./343_Gabroveanu_Razvan"):

        self.reset()

        game_tables = utils.extract_game(utils.get_image_paths(src_path,self.data_set_id))
        relevant_game_tables = utils.extract_relevant_game(game_tables)

        output_file_prefix = "/" + str(self.data_set_id) + "_"

        for i in tqdm(range(len(relevant_game_tables))):

            table = relevant_game_tables[i]
            table = cv.cvtColor(table, cv.COLOR_BGR2GRAY)
            _,table_binary = cv.threshold(table,65,255,cv.THRESH_BINARY_INV)

            result_dict = match_numbers(table_binary,8)

            for indexes,predicted_number in result_dict.items():
                row,col = indexes

                if self.table_configuration[row,col] != -1:
                    continue

                output = str(row+1) + chr(65 + col)+ " " + str(predicted_number)
                output_file_path = output_dest_path + output_file_prefix

                if i in range(0,9):
                    output_file_path = output_file_path + "0"

                output_file_path = output_file_path + str(i+1) + ".txt"

                with open(output_file_path,"w") as file:
                    file.write(output)

                self.table_configuration[row,col] = predicted_number

        with open(output_dest_path + "/" + str(self.data_set_id) + "_scores.txt","w") as file:
            pass

        with open(output_dest_path + "/" + str(self.data_set_id) + "_turns.txt","w") as file:
            pass

for i in range(4):
    solver = Solver(i+1)
    solver.solve()


100%|██████████| 50/50 [00:16<00:00,  3.02it/s]


[[-1 -1 -1 -1 -1 -1 -1  8 -1  5 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 10 -1  2 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1  8 -1  3 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 80 -1  6 -1 48 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 10 -1  9 -1 36 -1 -1]
 [-1 -1 -1  3 14 11  3  8  5  3 15 12 27 -1]
 [-1 -1 -1 -1 -1 -1  1  2  3  6  9  3 -1 -1]
 [-1 -1 -1 -1 -1  7  3  4  7  9 63 -1 -1 -1]
 [-1 -1 -1 -1  8 10  2  8 10 -1 54 -1 -1 -1]
 [-1 -1 -1  5  8  3  5 32 17 49 -1 -1 -1 -1]
 [-1 -1 -1 -1  0 -1 -1 40  7 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 72 10 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 70 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 60 -1 -1 -1 -1 -1]]


100%|██████████| 50/50 [00:16<00:00,  2.99it/s]


[[-1 -1 -1 -1 -1 -1 -1 32 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 18  8 10 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1  4 40 36  4 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 14 48 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1  2  5 10  8  2 10  8 -1 -1 -1]
 [-1 -1 -1 -1  6  2  4  6 10  4 -1 -1 -1 -1]
 [-1 36 16 12  4  3  1  2  8  6  9 15  6 90]
 [-1 -1 -1 -1 -1  5  3  4  7 10 70 -1 -1 -1]
 [-1 -1 -1 -1 35  8  2  6 21 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1  6 30 24 54 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1  2 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1  4 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1  2 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]]


100%|██████████| 50/50 [00:17<00:00,  2.86it/s]


[[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 10 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1  1 49 48  1 80 81 -1 -1 -1]
 [-1 -1  6 -1 -1 -1 -1  8  1  8 -1 -1 -1 -1]
 [-1 -1 10 35 25 10  4  6  0 10  8 -1 -1 -1]
 [20  4 16 12  4  3  1  2  1  2  3 -1 -1 -1]
 [-1 -1 -1 -1 21  7  3  4  1  5  5 -1 -1 -1]
 [-1 -1 -1 -1 -1 10 -1  2  2 -1 -1 -1 -1 -1]
 [-1 -1 -1 45 28 17 11  8  3 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1  7 -1 10  5 50 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 10 -1  2 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1  3 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]]


100%|██████████| 50/50 [00:17<00:00,  2.88it/s]

[[-1 -1 -1 -1 -1 -1 -1 32 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1  8 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 10 -1 40 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1  3 -1 48 -1  6 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 13 -1  8 -1  5 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 10 -1  6 -1 11 -1 -1 -1 -1]
 [-1 -1 -1 -1  4  3  1  2  3  6  9  3 12 15]
 [-1 -1 -1 -1 60  7  3  4  1  5  5 25  5  5]
 [-1 -1 -1 -1  6 10  4  6 -1  1 45 -1 -1 -1]
 [-1 -1 -1  7 10 17  7 24 -1  6 -1 -1 -1 -1]
 [-1 -1 -1 -1  4 -1 28 30 -1  7 -1 -1 -1 -1]
 [-1 -1 -1 -1 14 -1 21 54 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1  7 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1  3 -1 -1 -1 -1 -1 -1 -1]]
